name: Lint and test

on: [push, pull_request]

jobs:
    lint_and_test:
        strategy:
            fail-fast: false
            matrix:
                nodejs: [16]
                os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2-beta
              with:
                  node-version: ${{ matrix.nodejs }}

            - run: yarn install
            - run: yarn set version berry
            - run: yarn test:coverage
            - run: yarn lint
            - run: yarn build
